sudo: required
services:
    - docker

before_install:
  - docker build -t sikemausa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sikemausa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  # name of elasticBeanstalk app
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-190209119557"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY